

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    
